# Generated by Django 6.0.1 on 2026-02-07 05:46

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('ip', models.GenericIPAddressField(db_index=True, primary_key=True, serialize=False, verbose_name='IP  address')),
                ('reason', models.TextField()),
                ('datetime_added', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cooldown', models.DurationField(default=datetime.timedelta(seconds=7))),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('count', models.IntegerField(default=0, help_text='No of times this ip has been blocked')),
            ],
            options={
                'verbose_name': 'blocked IP',
                'verbose_name_plural': 'blocked IPs',
                'ordering': ['-last_seen', '-datetime_added', 'ip'],
            },
        ),
    ]
