# Generated by Django 6.0.1 on 2026-02-18 18:13

import aegis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedip',
            options={'get_latest_by': 'datetime_added', 'ordering': ['-last_seen', '-datetime_added', 'ip'], 'verbose_name': 'blocked IP', 'verbose_name_plural': 'blocked IPs'},
        ),
        migrations.RemoveField(
            model_name='blockedip',
            name='count',
        ),
        migrations.AddField(
            model_name='blockedip',
            name='tally',
            field=models.PositiveIntegerField(default=0, help_text='No of times this ip has been blocked'),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='cooldown',
            field=models.PositiveIntegerField(default=10, help_text='Cooldown period'),
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='IP address')),
                ('method_mask', models.PositiveIntegerField(db_index=True, default=aegis.models.HttpMethod['GET'])),
                ('bucket_level', models.FloatField(default=10.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('max_capacity', models.FloatField(default=10.0, help_text='Max bucket capacity')),
                ('refill_rate', models.FloatField(default=1.0)),
                ('expiration_days', models.PositiveIntegerField(default=7, help_text='Rate limit expiration date')),
            ],
            options={
                'unique_together': {('ip', 'method_mask')},
            },
        ),
    ]
