# Generated by Django 6.0.1 on 2026-03-25 05:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='IP address')),
            ],
        ),
        migrations.AlterModelOptions(
            name='blockedip',
            options={'get_latest_by': 'datetime_added', 'ordering': ['-last_seen', '-datetime_added', 'ip'], 'verbose_name': 'blocked IP', 'verbose_name_plural': 'blocked IPs'},
        ),
        migrations.RemoveField(
            model_name='blockedip',
            name='count',
        ),
        migrations.AddField(
            model_name='blockedip',
            name='allowed_methods',
            field=models.PositiveIntegerField(default=0, help_text='HTTP methods this IP can use'),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='tally',
            field=models.PositiveIntegerField(default=0, help_text='No of times this ip has been blocked'),
        ),
        migrations.AlterField(
            model_name='blockedip',
            name='cooldown',
            field=models.PositiveIntegerField(default=10, help_text='Cooldown period'),
        ),
        migrations.CreateModel(
            name='RateLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.PositiveIntegerField(choices=[(1, 'GET'), (2, 'HEAD'), (4, 'POST'), (8, 'PUT'), (16, 'DELETE'), (32, 'CONNECT'), (64, 'OPTIONS'), (128, 'TRACE'), (256, 'PATCH')])),
                ('max_capacity', models.FloatField(default=10.0)),
                ('bucket_level', models.FloatField(default=10.0)),
                ('refill_rate', models.FloatField(default=1.0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='aegis.ratelimit')),
            ],
            options={
                'unique_together': {('ip', 'method')},
            },
        ),
    ]
