# Generated by Django 6.0.1 on 2026-05-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0002_ratelimit_alter_blockedip_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalRateLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.PositiveIntegerField(choices=[(1, 'GET'), (2, 'HEAD'), (4, 'POST'), (8, 'PUT'), (16, 'DELETE'), (32, 'CONNECT'), (64, 'OPTIONS'), (128, 'TRACE'), (256, 'PATCH')], unique=True, verbose_name='HTTP Method defaults')),
                ('max_capacity', models.FloatField(default=10.0)),
                ('refill_rate', models.FloatField(default=1.0)),
            ],
        ),
    ]
