# Generated by Django 6.0.1 on 2026-02-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0002_alter_blockedip_options_remove_blockedip_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='allowed_methods',
            field=models.PositiveIntegerField(default=0, help_text='HTTP methods this IP can use'),
        ),
    ]
