# Generated by Django 6.0.1 on 2026-05-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0003_globalratelimitrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalratelimitrule',
            name='bucket_level',
            field=models.FloatField(default=10.0),
        ),
    ]
