# Generated by Django 6.0.1 on 2026-02-22 10:55

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0005_alter_blockedip_allowed_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedip',
            name='allowed_methods',
            field=django_enum.fields.SmallIntegerFlagField(blank=True, choices=[(0, 'NONE'), (1, 'GET'), (2, 'HEAD'), (4, 'POST'), (8, 'PUT'), (16, 'DELETE'), (32, 'CONNECT'), (64, 'OPTIONS'), (128, 'TRACE'), (256, 'PATCH')], default=0, help_text='HTTP methods this IP can use'),
        ),
    ]
