# Generated by Django 6.0.1 on 2026-02-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0006_alter_blockedip_allowed_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedip',
            name='allowed_methods',
            field=models.PositiveIntegerField(default=0, help_text='HTTP methods this IP can use'),
        ),
    ]
